---
title: "PA1_Reproducible_Research"
author: "Nsi J."
date: "21 mai 2017"
output: html_document
---

# Analyzing FitBit Data


About This was the first project for the Reproducible Research course in Coursera's Data Science specialization track. The purpose of the project was to answer a series of questions using data collected from a FitBit.

## Synopsis 
The purpose of this project was to practice:

loading and preprocessing data
imputing missing values
interpreting data to answer research questions
Data

The data for this assignment was downloaded from the course web site:  

##  Dataset and variables
Dataset: Activity monitoring data [52K]
The variables included in this dataset are:

steps: Number of steps taking in a 5-minute interval (missing values are coded as NA)

date: The date on which the measurement was taken in YYYY-MM-DD format

interval: Identifier for the 5-minute interval in which measurement was taken

The dataset is stored in a comma-separated-value (CSV) file and there are a total of 17,568 observations in this datase